### ISSUE TITLE
TypeError: einsum() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by outlookerr** [kamata1729/QATM_pytorch#8]
when I run
python qatm.py -s sample/sample1.jpg -t template --cuda

Result
import qatm_pytorch.py...
define model...
calculate score...
Traceback (most recent call last):
  File "qatm.py", line 46, in <module>
    scores, w_array, h_array, thresh_list = run_multi_sample(model, dataset)
  File "mod.py", line 333, in run_multi_sample
  File "mod.py", line 306, in run_one_sample
  File "mod.py", line 150, in __call__
TypeError: einsum() takes 2 positional arguments but 3 were given

I would appreciate if you give me any advice~

**Comment by JianliWei1995** [comment]
I update pytorch to the latest then it works.

**Comment by JianliWei1995** [comment]
> when I run
> python qatm.py -s sample/sample1.jpg -t template --cuda
> 
> Result
> import qatm_pytorch.py...
> define model...
> calculate score...
> Traceback (most recent call last):
> File "qatm.py", line 46, in
> scores, w_array, h_array, thresh_list = run_multi_sample(model, dataset)
> File "mod.py", line 333, in run_multi_sample
> File "mod.py", line 306, in run_one_sample
> File "mod.py", line 150, in **call**
> TypeError: einsum() takes 2 positional arguments but 3 were given
> 
> I would appreciate if you give me any advice~
I update pytorch to the latest then it works.
